version: '2'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: kt_team_test
    volumes:
      - .:/kt_team_test
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A kt_team_test worker -l info
    volumes:
      - .:/kt_team_test
    depends_on:
      - redis

  redis:
    image: "redis:alpine"